# Enable Display
CONFIG_ZMK_DISPLAY=y

# Enable Widgets (The "Status Bar")
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# Specific fix for the 1.3" OLED (sh1106 or ssd1306)
# Sometimes these need to be inverted or offset
CONFIG_SSD1306_REVERSE_MODE=y
