CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Unlock ZMK Studio by default
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# --- Power Management ---
# Enable deep sleep support
CONFIG_ZMK_SLEEP=y

# 10 minutes of inactivity before deep sleep (in milliseconds)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# 30 seconds of inactivity before entering "idle" (dims LEDs/lowers poll rate)
CONFIG_ZMK_IDLE_TIMEOUT=30000

#rgb
#CONFIG_ZMK_RGB_UNDERGLOW=y
#CONFIG_WS2812_STRIP=y
#CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
#CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=0
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=10
#CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
#CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
#CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
