# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

# Unlock ZMK Studio by default
CONFIG_ZMK_STUDIO_LOCKING=n

# --- Power Management ---
# Enable deep sleep support
CONFIG_ZMK_SLEEP=y

# 15 minutes of inactivity before deep sleep (in milliseconds)
# 15 * 60 * 1000 = 900000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# 30 seconds of inactivity before entering "idle" (dims LEDs/lowers poll rate)
CONFIG_ZMK_IDLE_TIMEOUT=30000
